# [Name, isVC, Catches, Stumpings, isC, isVC, Catches, Stumpings]

O = [["DP Conway", False, 0, 0, False, False, 0, 0],
     ["David Warner", False, 0, 0, False, False, 0, 0],
     ["Phil Salt", False, 0, 0, False, False, 0, 0],
     ["Faf du Plessis", False, 0, 0, False, False, 0, 0],
     ["Travis Head", False, 0, 0, False, False, 0, 0],
     ["Ruturaj Gaikwad", False, 0, 0, False, False, 0, 0],
     ["Prithvi Shaw", False, 0, 0, False, False, 0, 0],
     ["Shubman Gill", False, 0, 0, False, False, 0, 0],
     ["KL Rahul", False, 0, 0, False, False, 0, 0],
     ["Rohit Sharma", False, 0, 0, False, False, 0, 0],
     ["Shikhar Dhawan", False, 0, 0, False, False, 0, 0],
     ["Virat Kohli", False, 0, 0, False, False, 0, 0],
     ["Yashasvi Jaiswal", False, 0, 0, False, False, 0, 0],
     ["Mayank Agarwal", False, 0, 0, False, False, 0, 0],
     ["Anmolpreet Singh", False, 0, 0, False, False, 0, 0]]

W = [["Shai Hope", False, 0, 0, False, False, 0, 0],
     ["Tristan Stubbs", False, 0, 0, False, False, 0, 0],
     ["Matthew Wade", False, 0, 0, False, False, 0, 0],
     ["Rahmanullah Gurbaz", False, 0, 0, False, False, 0, 0],
     ["Quinton de Kock", False, 0, 0, False, False, 0, 0],
     ["Nicholas Pooran", False, 0, 0, False, False, 0, 0],
     ["Jonny Bairstow", False, 0, 0, False, False, 0, 0],
     ["Jos Buttler", False, 0, 0, False, False, 0, 0],
     ["Donovan Ferreira", False, 0, 0, False, False, 0, 0],
     ["Heinrich Klaasen", False, 0, 0, False, False, 0, 0],
     ["MS Dhoni", False, 0, 0, False, False, 0, 0],
     ["Aravelly Avanish", False, 0, 0, False, False, 0, 0],
     ["Rishabh Pant", False, 0, 0, False, False, 0, 0],
     ["Abishek Porel", False, 0, 0, False, False, 0, 0],
     ["Wriddhiman Saha", False, 0, 0, False, False, 0, 0],
     ["Robin Minz", False, 0, 0, False, False, 0, 0],
     ["Srikar Bharat", False, 0, 0, False, False, 0, 0],
     ["Ishan Kishan", False, 0, 0, False, False, 0, 0],
     ["Vishnu Vinod", False, 0, 0, False, False, 0, 0],
     ["Prabhsimran Singh", False, 0, 0, False, False, 0, 0],
     ["Jitesh Sharma", False, 0, 0, False, False, 0, 0],
     ["Anuj Rawat", False, 0, 0, False, False, 0, 0],
     ["Dinesh Karthik", False, 0, 0, False, False, 0, 0],
     ["Sanju Samson", False, 0, 0, False, False, 0, 0],
     ["Dhruv Jurel", False, 0, 0, False, False, 0, 0],
     ["Kunal Singh Rathore", False, 0, 0, False, False, 0, 0],
     ["Upendra Yadav", False, 0, 0, False, False, 0, 0]]

